# Generated by Django 4.2.4 on 2023-09-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_artist_artist_type_artist_biography_artist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
