# Generated by Django 4.2.4 on 2023-09-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_exhibit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_artist',
        ),
    ]
