# Generated by Django 4.2.4 on 2023-09-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_userprofile_is_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='media/artist_profile_pics/'),
        ),
    ]
