# Generated by Django 4.2.4 on 2023-09-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_artist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user_profile',
        ),
    ]
