# Generated by Django 4.2.4 on 2023-09-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_artist_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_type',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='website',
        ),
        migrations.AddField(
            model_name='artist',
            name='art_medium',
            field=models.CharField(blank=True, choices=[('painter', 'Painter'), ('drawing', 'Drawing'), ('sculpture', 'Sculpture'), ('graphic design', 'Graphic Design'), ('textile design', 'Textile Design'), ('photographer', 'Photographer'), ('architecture', 'Architecture')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='art_movement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='years_active',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
