# Generated by Django 4.2.4 on 2023-09-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_artist_artist_type_remove_artist_social_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='art_medium',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
